on: 
    release:
        types: [published,edited]
env:
  CGO_ENABLED: 0

name: Release qshell
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:  
          # windows/arm64 , darwin/arm sand darwin/386 seems useless 
          - goarch: "386"
            goos: darwin  
          - goarch: "arm"
            goos: darwin
          - goarch: "arm64"
            goos: windows  
    steps:
    - uses: actions/checkout@v2
    - name: Set APP_VERSION env
      run: echo ::set-env name=APP_VERSION::$(cat ${GITHUB_EVENT_PATH} | jq -r .release.tag_name )
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.20.1.linux-amd64.tar.gz"
        ldflags: -X "github.com/qiniu/qshell/v2/iqshell/common/version.version=${{ env.APP_VERSION }}" -extldflags "-static"
